
segmentation:
  trunk:
    color: [0,0,1]
    voxel_size: 0.008
    min_trunk_height: 0.5
    dbscan_eps: 0.02
    dbscan_min_samples: 15
    plane_fitting_thickness: 0.02
    smoothing_factor: 0.01
    interpolated_points: 400
  branch:
    primary:
      color: [ 0,1,0 ]
      voxel_size: 0.01
      min_branch_parent_distance: 0.1
      min_length: 0.05
      dbscan_eps: 0.03
      dbscan_min_samples: 5
      obstacle_threshold: 0.015
      plane_fitting_thickness: 0.01
      smoothing_factor: 0.02
      interpolated_points: 100
    secondary:
      color: [ 1,0,0 ]
      voxel_size: 0.000005
      min_branch_parent_distance: 0.06
      min_length: 0.02
      dbscan_eps: 0.03
      dbscan_min_samples: 4
      obstacle_threshold: 0.01
      plane_fitting_thickness: 0.005
      smoothing_factor: 0.03
      interpolated_points: 50


fitting:
  trunk: 1